version: "2"
services:
    splash:
        image: scrapinghub/splash:2.3.2
        ports:
            - "8050:8050"
            - "5023:5023"
    nginx:
        image: nginx:1.13.0-alpine
        ports:
            - "8080:8080"
        depends_on:
            - splash
        volumes:
            - .docker/nginx/volumes/conf.d/:/etc/nginx/conf.d
    wget:
        build:
          context: .
          dockerfile: .docker/wget/Dockerfile
        command: /bin/sh # とりあえず compose で起動させるために
        depends_on:
          - nginx
        volumes:
            - .docker/wget/volumes/saved_contents/:/saved_contents
